### ISSUE TITLE
Transport options not working?

### ISSUE THREAD

**Issue by edwardhorsford** [hyjin/bunyan-emailstream#2]
I have two issues:

Code won't run unless an empty transport options object is provided:
`var emailStream = new EmailStream(
// Nodemailer mailOptions
    {
        from: 'address',
        to: 'address'
    } ,{}
);`

I also can't seem to get authenticated smtp sending to work - it still seems to go via the unauthenticated route.

Any ideas?

**Comment by hyjin** [comment]
@edwardhorsford Thank you for the issue.
Yes, an empty transport options cause error, I will fix this soon. (And some broken part in readme, too)

Could you elaborate the transport options that you tried?
Did you add `type` property to transport options and its value is `SMTP`? (yeah, readme lacks this part...)

**Comment by edwardhorsford** [comment]
Thanks! Changing type to SMTP worked! This wasn't clear that it was needed from the nodemon logs. It basically looked like everything in the options was being ignored.

**Comment by edwardhorsford** [comment]
This is my code now. Would be great for something similar to be included in the readme - then with links out to nodemon for more complex usage.

`var emailStream = new EmailStream(
// Nodemailer mailOptions
    {
        from: 'sender address',
        to: 'remote address'
    }
// Nodemailer transportOptions
    ,{
        type: 'SMTP',
        service: 'gmail',
        auth: {
            user: 'username',
            pass: 'password'
        }
    }
);
`

**Comment by hyjin** [comment]
Nice idea! I will improve README.
Thank you for the suggestion!
